### ISSUE TITLE
syntax error, unexpected ')' - import issue

### ISSUE THREAD

**Issue by pseudozach** [Jorijn/bitcoin-bolt11#2]
Hi,

I had this strange issue when trying to import the library on linux with php7.2
```
use Jorijn\Bitcoin\Bolt11\Encoder\PaymentRequestDecoder;
PHP Fatal error:  Uncaught Error: Class 'PaymentRequestDecoder' not found in test3.php:32
Stack trace:
#0 {main}
  thrown in test3.php on line 32
PHP Parse error:  syntax error, unexpected ')' in /home/liqulgwv/public_html/vendor/jorijn/bitcoin-bolt11/src/Encoder/PaymentRequestDecoder.php on line 164
```

I fixed it by removing the single comma at this line:
```
        $toSign = Buffertools::concat(
            new Buffer($prefix),
            $this->wordsToBuffer($wordsWithoutSignature),   <--- removed this comma and library started working :)
        );
```

Note that I didn't see this issue in MacOS php7.3.

**Comment by Jorijn** [comment]
Hey @pseudozach 

The error is caused by the so-called "trailing comma in array" feature. It is supported since PHP 7.3.

PHP 7.3 is also the minimum required version supported for this library since PHP 7.2 is considered end-of-life. It won't receive any security updates anymore, so I suggest you upgrade the Linux server.

Please see https://www.php.net/supported-versions.php.

Good luck with the library. I like all the projects on your site! If you create something great with the library, do let me know. :-)

Jorijn

**Comment by pseudozach** [comment]
Thanks for this great library, it's very useful! 

I will definitely let you know about our rewards cash back site with Lightning withdrawals when it's announced soon :)

Thanks for the response,
